---
- name: Install proxmox
  hosts: proxmox
  become: yes
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Add an /etc/hosts entry for your IP address
     ansible.builtin.shell: echo "{{ ansible_host }} prox4m1.proxmox.com prox4m1" >> /etc/hosts
   - name: Add the Proxmox VE repository
     ansible.builtin.shell: echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
   - name: Add the Proxmox VE repository key as root
     ansible.builtin.shell: wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
   - name: Update your repository and system by running
     become: true
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400
   - name: Install Nginx
     ansible.builtin.apt:
       name: nginx
       state: present
   - name: Replace nginx.conf
     template:
       src=templates/nginx.conf
       dest=/etc/nginx/nginx.conf
   - name: Install the Proxmox VE Kernel
     ansible.builtin.apt:
       name: proxmox-default-kernel
       state: present
   - name: reboot host
     ansible.builtin.reboot:
       msg: "Rebooting machine ..."
   - name: Install the Proxmox VE packages
     ansible.builtin.apt:
       pkg:
        - proxmox-ve
        - postfix
        - open-iscsi
        - chrony
   - name: Remove the Debian Kernel
     ansible.builtin.apt:
       name: linux-image-amd64
       state: absent
   - name: Remove the Debian Kernel2
     ansible.builtin.apt:
       name: 'linux-image-6.1*'
       state: absent
   - name: Update and check grub2 config
     ansible.builtin.shell: update-grub